import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Language = "en" | "ar";
type Dictionary = Record<string, string>;

const en: Dictionary = {
  dashboard:"Dashboard", campaigns:"Campaigns", compose:"Compose", contacts:"Contacts", groups:"Groups", senders:"Sender Accounts", templates:"Templates", reports:"Reports", audit:"Audit Log", users:"Users", settings:"Settings",
  overview:"Overview", systemOnline:"System operational", notifications:"Notifications", noNotifications:"No new notifications", profile:"User profile", administrator:"Administrator", collapse:"Collapse navigation", expand:"Expand navigation", menu:"Open navigation", close:"Close",
  totalContacts:"Total Contacts", sent:"Sent", failed:"Failed", pending:"Pending", campaignOverview:"Campaign overview", recentCampaigns:"Recent campaigns", recentActivity:"Recent activity", sendingStatus:"Sending status", groupStatistics:"Group statistics", senderStatus:"Sender account status",
  noCampaignData:"No campaign data yet", noCampaignDataDesc:"Campaign performance will appear here after your first campaign is created.", createCampaign:"Create Campaign", noCampaigns:"No campaigns yet", noCampaignsDesc:"Create your first campaign to prepare an email for your recipient groups.", noActivity:"No recent activity", noActivityDesc:"System actions and delivery events will appear here.", noGroups:"No groups yet", noGroupsDesc:"Create a group to organize contacts and sender routing.", noSenders:"No sender accounts yet", noSendersDesc:"Connect a sender account before delivering email.", configureSender:"Configure sender", addGroup:"Add Group",
  search:"Search", filters:"Filters", status:"Status", date:"Date", group:"Group", sender:"Sender", allStatuses:"All statuses", allGroups:"All groups", allSenders:"All senders", campaign:"Campaign", subject:"Subject", recipients:"Recipients", created:"Created", actions:"Actions", clearFilters:"Clear filters",
  composeEmail:"Compose email", composeDesc:"Prepare an individual, private delivery for every recipient.", toGroups:"To / Groups", selectGroups:"Select recipient groups", noGroupsAvailable:"No groups are available yet.", createGroupFirst:"Create a group before composing your campaign.", emailSubject:"Email subject", subjectPlaceholder:"Enter a clear subject", message:"Message", messagePlaceholder:"Write your email…", template:"Template", noTemplate:"No template", attachments:"Attachments", addAttachment:"Add attachment", senderPreview:"Sender preview", selectedGroups:"Selected groups", senderRouting:"Sender routing", replyTo:"Reply-To", signature:"Signature", recipientCount:"Recipient count", notConfigured:"Not configured", smartPreview:"Smart Recipient Preview", reviewBeforeSending:"Review recipients and routing before sending.", individualDelivery:"Every recipient will receive an individual email. Recipient addresses are never exposed to others.", previewEmail:"Preview Email", schedule:"Schedule", sendNow:"Send Now", unavailable:"Unavailable until email delivery is connected.", draftSaved:"Draft changes are kept in this session.", formatting:"Formatting controls",
  noContacts:"No contacts yet", noContactsDesc:"Add your first contact to start building your recipient groups.", addContact:"Add Contact", importExcel:"Import Excel", importCsv:"Import CSV", exportCsv:"Export CSV", department:"Department", fullName:"Full Name", email:"Email", employeeId:"Employee ID", bulkActions:"Bulk actions", pagination:"Page 1 of 1",
  noTemplates:"No templates yet", noTemplatesDesc:"Create a reusable email layout for consistent communication.", createTemplate:"Create Template", noReports:"No reports available", noReportsDesc:"Delivery analytics will appear when real campaign results are available.", daily:"Daily", weekly:"Weekly", monthly:"Monthly", customRange:"Custom range", noAudit:"No audit events yet", noAuditDesc:"Security and administrative activity will be recorded here.", user:"User", action:"Action", description:"Description", dateTime:"Date / Time", ip:"IP address",
  noUsers:"No users yet", noUsersDesc:"Invite authorized team members and assign the appropriate role.", addUser:"Add User", role:"Role", permissions:"Permissions", accountStatus:"Account status", noSenderAccounts:"No sender accounts yet", noSenderAccountsDesc:"Add an approved SMTP sender to enable routing by group.", addSender:"Add Sender Account", testConnection:"Test connection", smtpHost:"SMTP Host", smtpPort:"SMTP Port", security:"Security", assignedGroup:"Assigned Group",
  campaignDetails:"Campaign details", campaignNotFound:"No campaign selected", campaignNotFoundDesc:"Campaign progress and delivery activity will appear after a campaign is created.", totalRecipients:"Total Recipients", successRate:"Success Rate", sendingTimeline:"Sending activity timeline", pause:"Pause", resume:"Resume", stop:"Stop", retryFailed:"Retry Failed",
  general:"General", smtp:"SMTP", emailSettings:"Email", notificationsSettings:"Notifications", appearance:"Appearance", language:"Language", system:"System", organizationName:"Organization name", timezone:"Timezone", saveChanges:"Save changes", settingsSaved:"Settings saved", defaultLanguage:"Default language", sessionTimeout:"Session timeout", requireTwoFactor:"Require two-factor authentication", operational:"Operational",
  loginTitle:"BFM Email Management System", signInDesc:"Secure access for authorized personnel", username:"Username", password:"Password", rememberMe:"Remember me", signIn:"Sign In", forgotPassword:"Forgot password?", authUnavailable:"Authentication will be available when the secure identity service is connected.", required:"This field is required", backToSystem:"Back to system",
  home:"Home", empty:"Empty", select:"Select", cancel:"Cancel", confirm:"Confirm", comingSoon:"Requires backend connection", bfm:"BFM", company:"Banyat Facilities Management", settingsDesc:"Configure platform behavior, security, and email infrastructure.", reportsDesc:"Review real delivery performance and operational trends.", contactsDesc:"Manage recipients, departments, and group membership.", campaignsDesc:"Plan, monitor, and control corporate email campaigns.", groupsDesc:"Organize contacts and map each group to an approved sender.", sendersDesc:"Manage SMTP infrastructure and sender routing securely.", templatesDesc:"Create and maintain reusable corporate email layouts.", auditDesc:"Review security-sensitive and administrative activity.", usersDesc:"Control access with clearly defined enterprise roles.", dashboardDesc:"Your email operations at a glance.", loading:"Loading"
};

const ar: Dictionary = {
  dashboard:"لوحة التحكم", campaigns:"الحملات", compose:"إنشاء رسالة", contacts:"جهات الاتصال", groups:"المجموعات", senders:"حسابات الإرسال", templates:"القوالب", reports:"التقارير", audit:"سجل التدقيق", users:"المستخدمون", settings:"الإعدادات",
  overview:"نظرة عامة", systemOnline:"النظام يعمل بكفاءة", notifications:"الإشعارات", noNotifications:"لا توجد إشعارات جديدة", profile:"ملف المستخدم", administrator:"مسؤول النظام", collapse:"طي القائمة", expand:"توسيع القائمة", menu:"فتح القائمة", close:"إغلاق",
  totalContacts:"إجمالي جهات الاتصال", sent:"تم الإرسال", failed:"فشل", pending:"قيد الانتظار", campaignOverview:"نظرة عامة على الحملات", recentCampaigns:"الحملات الأخيرة", recentActivity:"النشاط الأخير", sendingStatus:"حالة الإرسال", groupStatistics:"إحصاءات المجموعات", senderStatus:"حالة حسابات الإرسال",
  noCampaignData:"لا توجد بيانات حملات بعد", noCampaignDataDesc:"سيظهر أداء الحملات هنا بعد إنشاء أول حملة.", createCampaign:"إنشاء حملة", noCampaigns:"لا توجد حملات بعد", noCampaignsDesc:"أنشئ حملتك الأولى لإعداد رسالة لمجموعات المستلمين.", noActivity:"لا يوجد نشاط حديث", noActivityDesc:"ستظهر إجراءات النظام وأحداث التسليم هنا.", noGroups:"لا توجد مجموعات بعد", noGroupsDesc:"أنشئ مجموعة لتنظيم جهات الاتصال ومسارات الإرسال.", noSenders:"لا توجد حسابات إرسال بعد", noSendersDesc:"اربط حساب إرسال قبل تسليم البريد.", configureSender:"إعداد حساب إرسال", addGroup:"إضافة مجموعة",
  search:"بحث", filters:"عوامل التصفية", status:"الحالة", date:"التاريخ", group:"المجموعة", sender:"المرسل", allStatuses:"كل الحالات", allGroups:"كل المجموعات", allSenders:"كل المرسلين", campaign:"الحملة", subject:"الموضوع", recipients:"المستلمون", created:"تاريخ الإنشاء", actions:"الإجراءات", clearFilters:"مسح التصفية",
  composeEmail:"إنشاء رسالة", composeDesc:"جهّز رسالة خاصة ومنفصلة لكل مستلم.", toGroups:"إلى / المجموعات", selectGroups:"اختيار مجموعات المستلمين", noGroupsAvailable:"لا توجد مجموعات متاحة بعد.", createGroupFirst:"أنشئ مجموعة قبل إعداد الحملة.", emailSubject:"موضوع الرسالة", subjectPlaceholder:"أدخل موضوعًا واضحًا", message:"الرسالة", messagePlaceholder:"اكتب رسالتك…", template:"القالب", noTemplate:"بدون قالب", attachments:"المرفقات", addAttachment:"إضافة مرفق", senderPreview:"معاينة المرسل", selectedGroups:"المجموعات المحددة", senderRouting:"مسار المرسل", replyTo:"الرد إلى", signature:"التوقيع", recipientCount:"عدد المستلمين", notConfigured:"غير مُعد", smartPreview:"المعاينة الذكية للمستلمين", reviewBeforeSending:"راجع المستلمين ومسارات الإرسال قبل المتابعة.", individualDelivery:"سيستلم كل شخص رسالة منفصلة، ولن تظهر عناوين المستلمين للآخرين.", previewEmail:"معاينة الرسالة", schedule:"جدولة", sendNow:"إرسال الآن", unavailable:"غير متاح حتى يتم ربط خدمة إرسال البريد.", draftSaved:"تُحفظ تغييرات المسودة في هذه الجلسة.", formatting:"أدوات التنسيق",
  noContacts:"لا توجد جهات اتصال بعد", noContactsDesc:"أضف أول جهة اتصال لبدء إنشاء مجموعات المستلمين.", addContact:"إضافة جهة اتصال", importExcel:"استيراد Excel", importCsv:"استيراد CSV", exportCsv:"تصدير CSV", department:"القسم", fullName:"الاسم الكامل", email:"البريد الإلكتروني", employeeId:"الرقم الوظيفي", bulkActions:"إجراءات جماعية", pagination:"الصفحة 1 من 1",
  noTemplates:"لا توجد قوالب بعد", noTemplatesDesc:"أنشئ قالب بريد قابلًا لإعادة الاستخدام لتوحيد التواصل.", createTemplate:"إنشاء قالب", noReports:"لا توجد تقارير متاحة", noReportsDesc:"ستظهر تحليلات التسليم عند توفر نتائج حملات فعلية.", daily:"يومي", weekly:"أسبوعي", monthly:"شهري", customRange:"نطاق مخصص", noAudit:"لا توجد أحداث تدقيق بعد", noAuditDesc:"سيتم تسجيل الأنشطة الأمنية والإدارية هنا.", user:"المستخدم", action:"الإجراء", description:"الوصف", dateTime:"التاريخ / الوقت", ip:"عنوان IP",
  noUsers:"لا يوجد مستخدمون بعد", noUsersDesc:"ادعُ أعضاء الفريق المصرح لهم وحدد الدور المناسب.", addUser:"إضافة مستخدم", role:"الدور", permissions:"الصلاحيات", accountStatus:"حالة الحساب", noSenderAccounts:"لا توجد حسابات إرسال بعد", noSenderAccountsDesc:"أضف مرسل SMTP معتمدًا لتفعيل المسارات حسب المجموعة.", addSender:"إضافة حساب إرسال", testConnection:"اختبار الاتصال", smtpHost:"مضيف SMTP", smtpPort:"منفذ SMTP", security:"الأمان", assignedGroup:"المجموعة المرتبطة",
  campaignDetails:"تفاصيل الحملة", campaignNotFound:"لم يتم تحديد حملة", campaignNotFoundDesc:"سيظهر تقدم الحملة ونشاط التسليم بعد إنشاء حملة.", totalRecipients:"إجمالي المستلمين", successRate:"معدل النجاح", sendingTimeline:"الخط الزمني لنشاط الإرسال", pause:"إيقاف مؤقت", resume:"استئناف", stop:"إيقاف", retryFailed:"إعادة محاولة الفاشل",
  general:"عام", smtp:"SMTP", emailSettings:"البريد الإلكتروني", notificationsSettings:"الإشعارات", appearance:"المظهر", language:"اللغة", system:"النظام", organizationName:"اسم المنشأة", timezone:"المنطقة الزمنية", saveChanges:"حفظ التغييرات", settingsSaved:"تم حفظ الإعدادات", defaultLanguage:"اللغة الافتراضية", sessionTimeout:"مهلة الجلسة", requireTwoFactor:"فرض المصادقة الثنائية", operational:"يعمل",
  loginTitle:"نظام BFM لإدارة البريد الإلكتروني", signInDesc:"دخول آمن للموظفين المصرح لهم", username:"اسم المستخدم", password:"كلمة المرور", rememberMe:"تذكرني", signIn:"تسجيل الدخول", forgotPassword:"نسيت كلمة المرور؟", authUnavailable:"سيصبح تسجيل الدخول متاحًا بعد ربط خدمة الهوية الآمنة.", required:"هذا الحقل مطلوب", backToSystem:"العودة إلى النظام",
  home:"الرئيسية", empty:"فارغ", select:"اختيار", cancel:"إلغاء", confirm:"تأكيد", comingSoon:"يتطلب ربط النظام الخلفي", bfm:"BFM", company:"بنيات لإدارة المرافق", settingsDesc:"تهيئة سلوك المنصة والأمان وبنية البريد الإلكتروني.", reportsDesc:"راجع أداء التسليم الفعلي والاتجاهات التشغيلية.", contactsDesc:"إدارة المستلمين والأقسام وعضوية المجموعات.", campaignsDesc:"تخطيط حملات البريد المؤسسية ومراقبتها والتحكم بها.", groupsDesc:"نظم جهات الاتصال واربط كل مجموعة بمرسل معتمد.", sendersDesc:"إدارة بنية SMTP ومسارات الإرسال بأمان.", templatesDesc:"إنشاء قوالب البريد المؤسسية القابلة لإعادة الاستخدام.", auditDesc:"مراجعة الأنشطة الأمنية والإدارية الحساسة.", usersDesc:"التحكم في الوصول من خلال أدوار مؤسسية واضحة.", dashboardDesc:"عمليات البريد الإلكتروني في لمحة.", loading:"جارٍ التحميل"
};

const I18nContext = createContext<{ language: Language; setLanguage: (language: Language) => void; t: (key: string) => string }>({ language:"en", setLanguage:()=>undefined, t:(key)=>key });
export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  useEffect(() => { const saved = localStorage.getItem("bfm-language"); if (saved === "ar" || saved === "en") setLanguageState(saved); }, []);
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = language === "ar" ? "rtl" : "ltr"; localStorage.setItem("bfm-language", language); }, [language]);
  const value = useMemo(() => ({ language, setLanguage:setLanguageState, t:(key:string)=>(language === "ar" ? ar : en)[key] ?? key }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n() { return useContext(I18nContext); }
