import * as Dialog from "@radix-ui/react-dialog";
import * as Tooltip from "@radix-ui/react-tooltip";
import { LoaderCircle, X, type LucideIcon } from "lucide-react";
import { forwardRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export const Button = forwardRef<HTMLButtonElement, ButtonHTMLAttributes<HTMLButtonElement> & { variant?:"primary"|"secondary"|"ghost"|"danger"; size?:"sm"|"md"|"icon"; loading?:boolean }>(({ className, variant="primary", size="md", loading, children, disabled, ...props }, ref) => <button ref={ref} disabled={disabled || loading} className={cn("inline-flex shrink-0 items-center justify-center gap-2 rounded-lg font-semibold transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 active:scale-[.98] disabled:pointer-events-none disabled:opacity-50", variant === "primary" && "bg-primary text-primary-foreground shadow-sm hover:bg-primary/90 hover:shadow-md", variant === "secondary" && "border border-border bg-background text-foreground hover:bg-accent", variant === "ghost" && "text-muted-foreground hover:bg-accent hover:text-foreground", variant === "danger" && "bg-destructive text-destructive-foreground hover:bg-destructive/90", size === "sm" && "h-8 px-3 text-xs", size === "md" && "h-10 px-4 text-sm", size === "icon" && "size-10", className)} {...props}>{loading && <LoaderCircle className="size-4 animate-spin" />}{children}</button>);
Button.displayName="Button";
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({className,...props},ref)=><input ref={ref} className={cn("h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground shadow-xs outline-none transition focus:border-ring focus:ring-3 focus:ring-ring/15 placeholder:text-muted-foreground",className)} {...props}/>); Input.displayName="Input";
export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(({className,...props},ref)=><select ref={ref} className={cn("h-10 rounded-lg border border-input bg-background px-3 text-sm text-foreground outline-none transition focus:border-ring focus:ring-3 focus:ring-ring/15",className)} {...props}/>); Select.displayName="Select";
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({className,...props},ref)=><textarea ref={ref} className={cn("w-full resize-none rounded-lg border border-input bg-background px-3 py-3 text-sm text-foreground outline-none transition focus:border-ring focus:ring-3 focus:ring-ring/15 placeholder:text-muted-foreground",className)} {...props}/>); Textarea.displayName="Textarea";
export function Card({children,className}:{children:ReactNode;className?:string|undefined}){return <section className={cn("rounded-xl border border-border bg-card text-card-foreground shadow-card",className)}>{children}</section>}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"|"info"}){return <span className={cn("inline-flex items-center rounded-md px-2 py-1 text-[11px] font-bold uppercase tracking-wide",tone==="neutral"&&"bg-muted text-muted-foreground",tone==="success"&&"bg-success-soft text-success",tone==="warning"&&"bg-warning-soft text-warning",tone==="danger"&&"bg-danger-soft text-danger",tone==="info"&&"bg-info-soft text-info")}>{children}</span>}
export function EmptyState({icon:Icon,title,description,action}:{icon:LucideIcon;title:string;description:string;action?:ReactNode}){return <div className="flex min-h-52 flex-col items-center justify-center px-5 py-10 text-center"><div className="mb-4 grid size-12 place-items-center rounded-xl border border-border bg-muted text-primary"><Icon className="size-5"/></div><h3 className="text-sm font-bold text-foreground">{title}</h3><p className="mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function PageHeader({title,description,actions}:{title:string;description:string;actions?:ReactNode}){return <header className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4"><div className="min-w-0"><h1 className="truncate text-2xl font-bold text-foreground sm:text-[28px]">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{actions&&<div className="flex shrink-0 flex-wrap items-center justify-end gap-2">{actions}</div>}</header>}
export function Modal({open,onOpenChange,title,description,children,footer}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description?:string;children:ReactNode;footer?:ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-overlay backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=open]:fade-in data-[state=closed]:fade-out"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-xl border border-border bg-card p-6 shadow-dialog data-[state=open]:animate-in data-[state=open]:fade-in data-[state=open]:zoom-in-95"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div className="min-w-0"><Dialog.Title className="text-lg font-bold">{title}</Dialog.Title>{description&&<Dialog.Description className="mt-1 text-sm text-muted-foreground">{description}</Dialog.Description>}</div><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="Close"><X className="size-4"/></Button></Dialog.Close></div><div className="mt-6">{children}</div>{footer&&<div className="mt-6 flex flex-wrap justify-end gap-2 border-t border-border pt-4">{footer}</div>}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export function Tip({label,children}:{label:string;children:ReactNode}){return <Tooltip.Provider delayDuration={250}><Tooltip.Root><Tooltip.Trigger asChild>{children}</Tooltip.Trigger><Tooltip.Portal><Tooltip.Content sideOffset={8} className="z-[70] rounded-md bg-tooltip px-2.5 py-1.5 text-xs text-tooltip-foreground shadow-lg animate-in fade-in zoom-in-95">{label}<Tooltip.Arrow className="fill-tooltip"/></Tooltip.Content></Tooltip.Portal></Tooltip.Root></Tooltip.Provider>}
